import { create } from 'zustand';

// Translations for the app
const translations = {
  en: {
    home: 'Home',
    tutorials: 'Tutorials',
    contact: 'Contact',
    login: 'Login',
    signup: 'Sign Up',
    dashboard: 'Dashboard',
    profile: 'Profile',
    logout: 'Logout',
    allTutorials: 'All Tutorials',
    browseTutorials: 'Browse all free engineering tutorials',
    difficulty: 'Difficulty',
    allLevels: 'All Levels',
    all: 'All',
    filterBy: 'Filter by:',
    prev: '← Prev',
    next: 'Next →',
    noTutorials: 'No tutorials found',
    tryAdjusting: 'Try adjusting your filters',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    searchTutorials: 'Search tutorials...',
    learnEngineering: 'Learn Engineering Online',
    engineering: 'Engineering',
    tutorials_desc: 'Free, comprehensive engineering tutorials across Electrical, Civil, Mechanical, Computer, Chemical Engineering and more.',
    minRead: 'min read',
    page: 'Page',
    of: 'of',
    available: 'available',
    heroBadge: 'Free engineering education platform',
    heroTitleLine1: 'Master Engineering Concepts',
    heroTitleLine2: 'One Tutorial at a Time',
    heroSubtitle: 'Structured, in-depth tutorials across all engineering disciplines. Learn at your own pace, track your progress, test your knowledge.',
    browseTutorials: 'Browse Tutorials',
    createFreeAccount: 'Create Free Account',
    featureFree: 'Free Forever',
    featureQuiz: 'Quiz System',
    featureProgress: 'Progress Tracking',
    featureDisciplines: 'All Disciplines',
    disciplinesHeading: 'Engineering Disciplines',
    disciplinesSubheading: 'Choose your field and start learning today',
    featuredTutorials: 'Featured Tutorials',
    latestTutorials: 'Latest Tutorials',
    curatedContent: 'Carefully curated engineering content',
    noTutorialsYet: 'No tutorials yet',
    tutorialsWillAppear: 'Tutorials will appear here once published by authors.',
    whyHeading: 'Why Engineering & Me?',
    whySubtitle: 'Built for serious engineering learners',
    structuredLearning: 'Structured Learning',
    knowledgeQuizzes: 'Knowledge Quizzes',
    progressTracking: 'Progress Tracking',
    dailyStreaks: 'Daily Streaks',
    allDisciplines: 'All Disciplines',
    completelyFree: 'Completely Free',
    stayUpdated: 'Stay Updated',
    getLatest: 'Get the latest engineering tutorials, tips, and resources delivered to your inbox. Join thousands of engineers learning every week.',
    subscribe: 'Subscribe',
    subscribed: 'Subscribed! Check your inbox.',
    newsletterPrivacy: 'No spam. Unsubscribe anytime. See our Privacy Policy.',
    newsletter: 'Newsletter',
    footerNewsletter: 'Get the latest tutorials delivered to your inbox.',
    adsenseNotice: 'This site uses Google AdSense to display ads. By using this site, you agree to our',
    privacyPolicy: 'Privacy Policy',
    cookiePolicy: 'Cookie Policy',
    and: 'and',
    cookieBannerCopy: 'We use cookies to enhance your experience and show relevant ads. By clicking "Accept", you consent to our use of cookies.',
    learnMore: 'Learn more',
    decline: 'Decline',
    acceptAll: 'Accept All',
  },
  es: {
    home: 'Inicio',
    tutorials: 'Tutoriales',
    contact: 'Contacto',
    login: 'Iniciar sesión',
    signup: 'Registrarse',
    dashboard: 'Panel',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
    allTutorials: 'Todos los Tutoriales',
    browseTutorials: 'Explora todos los tutoriales de ingeniería gratuitos',
    difficulty: 'Dificultad',
    allLevels: 'Todos los Niveles',
    all: 'Todos',
    filterBy: 'Filtrar por:',
    prev: '← Anterior',
    next: 'Siguiente →',
    noTutorials: 'No se encontraron tutoriales',
    tryAdjusting: 'Intenta ajustar tus filtros',
    language: 'Idioma',
    theme: 'Tema',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    searchTutorials: 'Buscar tutoriales...',
    learnEngineering: 'Aprende Ingeniería en Línea',
    engineering: 'Ingeniería',
    tutorials_desc: 'Tutoriales de ingeniería gratuitos y completos en Ingeniería Eléctrica, Civil, Mecánica, Informática, Química y más.',
    minRead: 'min de lectura',
    page: 'Página',
    of: 'de',
    available: 'disponibles',
    heroBadge: 'Plataforma gratuita de educación en ingeniería',
    heroTitleLine1: 'Domina los conceptos de ingeniería',
    heroTitleLine2: 'Un tutorial a la vez',
    heroSubtitle: 'Tutoriales estructurados y profundos en todas las disciplinas de la ingeniería. Aprende a tu propio ritmo, realiza un seguimiento de tu progreso y prueba tus conocimientos.',
    browseTutorials: 'Explorar tutoriales',
    createFreeAccount: 'Crear cuenta gratuita',
    featureFree: 'Gratis para siempre',
    featureQuiz: 'Sistema de cuestionarios',
    featureProgress: 'Seguimiento de progreso',
    featureDisciplines: 'Todas las disciplinas',
    disciplinesHeading: 'Disciplinas de ingeniería',
    disciplinesSubheading: 'Elige tu campo y comienza a aprender hoy',
    featuredTutorials: 'Tutoriales destacados',
    latestTutorials: 'Últimos tutoriales',
    curatedContent: 'Contenido de ingeniería cuidadosamente seleccionado',
    noTutorialsYet: 'Aún no hay tutoriales',
    tutorialsWillAppear: 'Los tutoriales aparecerán aquí una vez que los autores los publiquen.',
    whyHeading: '¿Por qué Engineering & Me?',
    whySubtitle: 'Diseñado para estudiantes de ingeniería serios',
    structuredLearning: 'Aprendizaje estructurado',
    knowledgeQuizzes: 'Cuestionarios de conocimiento',
    progressTracking: 'Seguimiento de progreso',
    dailyStreaks: 'Rachas diarias',
    allDisciplines: 'Todas las disciplinas',
    completelyFree: 'Totalmente gratis',
    stayUpdated: 'Mantente actualizado',
    getLatest: 'Recibe los últimos tutoriales de ingeniería, consejos y recursos en tu bandeja de entrada. Únete a miles de ingenieros que aprenden cada semana.',
    subscribe: 'Suscribirse',
    subscribed: '¡Suscrito! Comprueba tu bandeja de entrada.',
    newsletterPrivacy: 'Sin spam. Cancela la suscripción en cualquier momento. Consulta nuestra Política de privacidad.',
  },
  fr: {
    home: 'Accueil',
    tutorials: 'Tutoriels',
    contact: 'Contact',
    login: 'Connexion',
    signup: 'Inscription',
    dashboard: 'Tableau de bord',
    profile: 'Profil',
    logout: 'Déconnexion',
    allTutorials: 'Tous les Tutoriels',
    browseTutorials: 'Consultez tous les tutoriels d\'ingénierie gratuits',
    difficulty: 'Difficulté',
    allLevels: 'Tous les Niveaux',
    all: 'Tous',
    filterBy: 'Filtrer par :',
    prev: '← Précédent',
    next: 'Suivant →',
    noTutorials: 'Aucun tutoriel trouvé',
    tryAdjusting: 'Essayez d\'ajuster vos filtres',
    language: 'Langue',
    theme: 'Thème',
    darkMode: 'Mode Sombre',
    lightMode: 'Mode Clair',
    searchTutorials: 'Rechercher des tutoriels...',
    learnEngineering: 'Apprenez l\'Ingénierie en Ligne',
    engineering: 'Ingénierie',
    tutorials_desc: 'Tutoriels d\'ingénierie gratuits et complets en Génie Électrique, Civil, Mécanique, Informatique, Chimie et plus.',
    minRead: 'min de lecture',
    page: 'Page',
    of: 'de',
    available: 'disponibles',
    heroBadge: 'Plateforme d\'éducation en ingénierie gratuite',
    heroTitleLine1: 'Maîtrisez les concepts d\'ingénierie',
    heroTitleLine2: 'Un tutoriel à la fois',
    heroSubtitle: 'Tutoriels structurés et approfondis dans toutes les disciplines de l\'ingénierie. Apprenez à votre rythme, suivez vos progrès et testez vos connaissances.',
    browseTutorials: 'Parcourir les tutoriels',
    createFreeAccount: 'Créer un compte gratuit',
    featureFree: 'Gratuit pour toujours',
    featureQuiz: 'Système de quiz',
    featureProgress: 'Suivi des progrès',
    featureDisciplines: 'Toutes les disciplines',
    disciplinesHeading: 'Disciplines d\'ingénierie',
    disciplinesSubheading: 'Choisissez votre domaine et commencez à apprendre aujourd\'hui',
    featuredTutorials: 'Tutoriels en vedette',
    latestTutorials: 'Derniers tutoriels',
    curatedContent: 'Contenu d\'ingénierie soigneusement sélectionné',
    noTutorialsYet: 'Pas encore de tutoriels',
    tutorialsWillAppear: 'Les tutoriels apparaîtront ici une fois publiés par les auteurs.',
    whyHeading: 'Pourquoi Engineering & Me ?',
    whySubtitle: 'Conçu pour les apprenants sérieux en ingénierie',
    structuredLearning: 'Apprentissage structuré',
    knowledgeQuizzes: 'Quiz de connaissances',
    progressTracking: 'Suivi des progrès',
    dailyStreaks: 'Séries quotidiennes',
    allDisciplines: 'Toutes les disciplines',
    completelyFree: 'Entièrement gratuit',
    stayUpdated: 'Restez informé',
    getLatest: 'Recevez les derniers tutoriels d\'ingénierie, conseils et ressources dans votre boîte de réception. Rejoignez des milliers d\'ingénieurs qui apprennent chaque semaine.',
    subscribe: 'S\'abonner',
    subscribed: 'Abonné ! Vérifiez votre boîte de réception.',
    newsletterPrivacy: 'Pas de spam. Désabonnez-vous à tout moment. Consultez notre politique de confidentialité.',
    newsletter: 'Newsletter',
    footerNewsletter: 'Recevez les derniers tutoriels dans votre boîte de réception.',
    adsenseNotice: 'Ce site utilise Google AdSense pour afficher des annonces. En utilisant ce site, vous acceptez notre',
    privacyPolicy: 'Politique de confidentialité',
    cookiePolicy: 'Politique de cookies',
    and: 'et',
    cookieBannerCopy: 'Nous utilisons des cookies pour améliorer votre expérience et afficher des annonces pertinentes. En cliquant sur « Accepter », vous acceptez notre utilisation des cookies.',
    learnMore: 'En savoir plus',
    decline: 'Refuser',
    acceptAll: 'Tout accepter',
  },
  de: {
    home: 'Startseite',
    tutorials: 'Tutorials',
    contact: 'Kontakt',
    login: 'Anmelden',
    signup: 'Registrieren',
    dashboard: 'Armaturenbrett',
    profile: 'Profil',
    logout: 'Abmelden',
    allTutorials: 'Alle Tutorials',
    browseTutorials: 'Kostenlose Ingenieur-Tutorials durchsuchen',
    difficulty: 'Schwierigkeit',
    allLevels: 'Alle Stufen',
    all: 'Alle',
    filterBy: 'Filtern nach:',
    prev: '← Zurück',
    next: 'Weiter →',
    noTutorials: 'Keine Tutorials gefunden',
    tryAdjusting: 'Versuchen Sie, Ihre Filter anzupassen',
    language: 'Sprache',
    theme: 'Thema',
    darkMode: 'Dunkler Modus',
    lightMode: 'Heller Modus',
    searchTutorials: 'Tutorials durchsuchen...',
    learnEngineering: 'Ingenieurwissenschaften Online Lernen',
    engineering: 'Ingenieurwissenschaften',
    tutorials_desc: 'Kostenlose und umfassende Ingenieur-Tutorials in Elektro-, Bau-, Maschinen-, Informatik- und Chemieingenieurwesen und mehr.',
    minRead: 'Min. Lesezeit',
    page: 'Seite',
    of: 'von',
    available: 'verfügbar',
    heroBadge: 'Kostenlose Ingenieurausbildungsplattform',
    heroTitleLine1: 'Beherrsche Ingenieurskonzepte',
    heroTitleLine2: 'Ein Tutorial nach dem anderen',
    heroSubtitle: 'Strukturierte, tiefgehende Tutorials in allen Ingenieurdisziplinen. Lerne in deinem eigenen Tempo, verfolge deinen Fortschritt und teste dein Wissen.',
    browseTutorials: 'Tutorials durchsuchen',
    createFreeAccount: 'Kostenloses Konto erstellen',
    featureFree: 'Für immer kostenlos',
    featureQuiz: 'Quiz-System',
    featureProgress: 'Fortschrittsverfolgung',
    featureDisciplines: 'Alle Disziplinen',
    disciplinesHeading: 'Ingenieurdisziplinen',
    disciplinesSubheading: 'Wähle dein Fachgebiet und beginne noch heute zu lernen',
    featuredTutorials: 'Ausgewählte Tutorials',
    latestTutorials: 'Neueste Tutorials',
    curatedContent: 'Sorgfältig kuratierte Ingenieurinhalte',
    noTutorialsYet: 'Noch keine Tutorials',
    tutorialsWillAppear: 'Tutorials erscheinen hier, sobald Autoren sie veröffentlichen.',
    whyHeading: 'Warum Engineering & Me?',
    whySubtitle: 'Entwickelt für ernsthafte Ingenieurlernende',
    structuredLearning: 'Strukturiertes Lernen',
    knowledgeQuizzes: 'Wissens-Quiz',
    progressTracking: 'Fortschrittsverfolgung',
    dailyStreaks: 'Tägliche Serien',
    allDisciplines: 'Alle Disziplinen',
    completelyFree: 'Völlig kostenlos',
    stayUpdated: 'Bleiben Sie auf dem Laufenden',
    getLatest: 'Erhalten Sie die neuesten Ingenieur-Tutorials, Tipps und Ressourcen in Ihren Posteingang. Schließen Sie sich Tausenden von Ingenieuren an, die jede Woche lernen.',
    subscribe: 'Abonnieren',
    subscribed: 'Abonniert! Überprüfen Sie Ihren Posteingang.',
    newsletterPrivacy: 'Kein Spam. Jederzeit abbestellen. Siehe Datenschutzrichtlinie.',
    newsletter: 'Newsletter',
    footerNewsletter: 'Erhalten Sie die neuesten Tutorials in Ihrem Posteingang.',
    adsenseNotice: 'Diese Website verwendet Google AdSense, um Anzeigen anzuzeigen. Durch die Nutzung dieser Website stimmen Sie unserer',
    privacyPolicy: 'Datenschutzrichtlinie',
    cookiePolicy: 'Cookie-Richtlinie',
    and: 'und',
    cookieBannerCopy: 'Wir verwenden Cookies, um Ihre Erfahrung zu verbessern und relevante Anzeigen zu zeigen. Durch Klicken auf "Alle akzeptieren" stimmen Sie unserer Verwendung von Cookies zu.',
    learnMore: 'Mehr erfahren',
    decline: 'Ablehnen',
    acceptAll: 'Alle akzeptieren',
  },
};

export const useLanguageStore = create((set) => ({
  language: 'en',
  initLanguage: () => {
    if (typeof window !== 'undefined') {
      const cookieMatch = document.cookie.match(/(?:^|; )language=([^;]+)/);
      const saved = (cookieMatch && decodeURIComponent(cookieMatch[1])) || localStorage.getItem('language') || 'en';
      set({ language: saved });
      document.documentElement.setAttribute('lang', saved);
    }
  },
  setLanguage: (lang) => {
    if (translations[lang]) {
      localStorage.setItem('language', lang);
      document.documentElement.setAttribute('lang', lang);
      // also set cookie so server components can read the language
      try { document.cookie = `language=${encodeURIComponent(lang)}; path=/; max-age=${60 * 60 * 24 * 365}`; } catch (e) {}
      set({ language: lang });
    }
  },
  t: (key) => {
    const state = useLanguageStore.getState();
    return translations[state.language]?.[key] || translations.en[key] || key;
  },
}));

export const getTranslation = (lang, key) => {
  return translations[lang]?.[key] || translations.en[key] || key;
};

export const supportedLanguages = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
];
